# Generated by Django 4.2.7 on 2023-12-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_newuser_email_alter_newuser_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newuser',
            new_name='user',
        ),
    ]
