# Generated by Django 4.2.7 on 2023-12-09 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='CustomUser',
        ),
    ]
